---
sudo: required
services:
    - docker
language: generic

env:
  CODECOV_UPLOADER=codecov

install:
    - pip install --user 'click<8.0.0'
    - pip install --user covimerage==0.2.1
    - |
        curl -fLso "${CODECOV_UPLOADER}" https://codecov.io/bash;
        VERSION=$(grep -o 'VERSION=\"[0-9\.]*\"' "${CODECOV_UPLOADER}" | cut -d'"' -f2);
        for i in 1 256 512
        do
            shasum -a $i -c <(curl -s "https://raw.githubusercontent.com/codecov/codecov-bash/${VERSION}/SHA${i}SUM") | grep -w "${CODECOV_UPLOADER}: OK"
        done

script:
    - ./run_tests.sh --profile

    # Validate Codecov configuration
    - curl --data-binary @.codecov.yml https://codecov.io/validate | tee codecov_validation
    - head -n 1 codecov_validation | grep 'Valid!'

after_success: |
    set -eo pipefail
    profile_file=$(ls | grep 'profile_file.*0\.4\.3')
    python -m covimerage write_coverage ${profile_file}
    sed -i "s,/testplugin/,$PWD/,g" .coverage_covimerage
    python -m covimerage -vv xml
    python -m covimerage report -m
    bash "${CODECOV_UPLOADER}" -X search -X gcov -X coveragepy -f coverage.xml
